name: CI/CD â†’ GCE VM
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: ${{ secrets.GCE_REMOTE_DIR }}
      SSH_USER: ${{ secrets.GCE_SSH_USER }}
      SSH_HOST: ${{ secrets.GCE_SSH_HOST }}
      SSH_PORT: ${{ secrets.GCE_SSH_PORT || '22' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ env.SSH_PORT }} ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Clone repo and setup docker 
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          port: ${{ env.SSH_PORT }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          run: |
            sudo apt update
            git clone https://github.com/twbs/bootstrap.git
            sudo apt install docker -y
            sudo systemctl start docker
            sudo systemctl status docker
            docker build -t archit:v1 .
            docker run archit:v1
